add_executable(geometry_example geometry_example.cpp)
target_link_libraries(geometry_example PRIVATE geometry3d)

add_executable(generic_composite_example generic_composite_example.cpp)
target_link_libraries(generic_composite_example PRIVATE composite)

add_executable(kdtree_example kdtree_example.cpp)
target_link_libraries(kdtree_example PRIVATE geometry3d)

add_executable(obb_example obb_example.cpp)
target_link_libraries(obb_example PRIVATE geometry3d)



